import type { Patient, Appointment, MLScreeningOutput } from './types';

export const DEMO_PATIENTS: Patient[] = [
  {
    id: 'PT-10021',
    name: 'Rajesh Kumar Verma',
    age: 58,
    gender: 'M',
    phone: '+91 98765 43210',
    diabetesType: 'Type 2',
    diabetesDuration: 12,
    hba1c: 8.4,
    currentMedication: 'Metformin 1000mg + Glimepiride 2mg',
    phcLocation: 'Khed PHC, Pune District',
    eye: 'Both',
    screeningDate: '2026-09-02',
    screeningTime: '09:14',
    imageQuality: {
      focus: 94,
      illumination: 88,
      fieldOfView: 92,
      overall: 'gradable',
      score: 91,
    },
    drLevel: 2,
    drLabel: 'Moderate Non-Proliferative Diabetic Retinopathy',
    confidence: 93.1,
    confidenceTier: 'standard',
    referable: true,
    aiStatus: 'complete',
    reviewStatus: 'pending',
    lesions: {
      microaneurysms: { detected: true, count: 14, confidence: 91, region: 'Pericentral and Inferior Temporal' },
      hemorrhages: { detected: true, count: 6, confidence: 87, region: 'Inferior Temporal Quadrant' },
      exudates: { detected: true, count: 3, confidence: 90, region: 'Parafoveal Area' },
      neovascularization: { detected: false, confidence: 88 },
    },
    retinalStructures: {
      opticDisc: { detected: true, confidence: 97, location: '(265, 188)' },
      fovea: { detected: true, confidence: 94, location: '(150, 202)' },
      vessels: { segmented: true, confidence: 92 },
    },
    whyFlagged: [
      'Multiple microaneurysms (14 count) detected across 2 quadrants',
      'Scattered dot-blot hemorrhages (6 count) in inferior temporal region',
      'Hard exudate cluster adjacent to the macular vascular arcade',
      'Exceeds referral threshold (ICDR Level 2+) — requires clinical review',
    ],
    referral: {
      required: true,
      priority: 'high',
      center: 'District Eye Hospital, Aundh, Pune',
      appointmentDate: '2026-09-12',
      appointmentTime: '10:30 AM',
      followUpDate: '2026-10-12',
      reason: 'Moderate NPDR with macular proximity exudates — specialist dilated fundus examination and OCT evaluation recommended.',
    },
    auditTrail: [
      {
        id: 'AT-01',
        timestamp: '2026-09-02 09:10',
        action: 'registered',
        actor: 'Anjali Deshmukh (ASHA)',
        actorRole: 'health_worker',
        details: 'Patient registered at Khed PHC field screening camp.',
      },
      {
        id: 'AT-02',
        timestamp: '2026-09-02 09:14',
        action: 'analyzed',
        actor: 'NetraRakshaq AI Engine v1.2',
        actorRole: 'AI Engine',
        details: 'Image quality verified gradable (91%). Model prediction: Moderate NPDR (Level 2), 93.1% confidence. Referable case flagged.',
      },
    ],
  },
  {
    id: 'PT-10022',
    name: 'Sunita Devi Sharma',
    age: 45,
    gender: 'F',
    phone: '+91 87654 32109',
    diabetesType: 'Type 2',
    diabetesDuration: 6,
    hba1c: 7.1,
    currentMedication: 'Metformin 500mg',
    phcLocation: 'Shirur Sub-District Center',
    eye: 'OD',
    screeningDate: '2026-09-02',
    screeningTime: '09:32',
    imageQuality: {
      focus: 87,
      illumination: 82,
      fieldOfView: 89,
      overall: 'gradable',
      score: 86,
    },
    drLevel: 1,
    drLabel: 'Mild Non-Proliferative Diabetic Retinopathy',
    confidence: 88.4,
    confidenceTier: 'standard',
    referable: false,
    aiStatus: 'complete',
    reviewStatus: 'reviewed',
    reviewedBy: 'Dr. R. Mehta (Ophthalmologist)',
    reviewedAt: '2026-09-02 10:15',
    reviewNotes: 'Verified mild NPDR. Isolated microaneurysms only. No macular threat. Glycemic control counseling given. Annual follow-up scheduled.',
    lesions: {
      microaneurysms: { detected: true, count: 4, confidence: 84, region: 'Superior Temporal' },
      hemorrhages: { detected: false, count: 0, confidence: 91 },
      exudates: { detected: false, count: 0, confidence: 89 },
      neovascularization: { detected: false, confidence: 95 },
    },
    retinalStructures: {
      opticDisc: { detected: true, confidence: 96, location: '(268, 185)' },
      fovea: { detected: true, confidence: 92, location: '(148, 200)' },
      vessels: { segmented: true, confidence: 90 },
    },
    whyFlagged: [
      'Isolated microaneurysms (4 count) without retinal hemorrhages',
      'Foveal reflex sharp and intact without lipid deposition',
      'Non-referable threshold per ICDR guidelines (Level 1)',
    ],
    referral: {
      required: false,
      priority: 'followup',
      center: 'Shirur PHC Health Center',
      followUpDate: '2027-09-02',
      reason: 'Routine 12-month diabetic retinal screening follow-up.',
    },
    auditTrail: [
      {
        id: 'AT-10',
        timestamp: '2026-09-02 09:30',
        action: 'registered',
        actor: 'Pooja Kadam (ANM)',
        actorRole: 'health_worker',
        details: 'Patient registered for routine diabetes eye check.',
      },
      {
        id: 'AT-11',
        timestamp: '2026-09-02 09:32',
        action: 'analyzed',
        actor: 'NetraRakshaq AI Engine v1.2',
        actorRole: 'AI Engine',
        details: 'Image quality gradable (86%). Predicted Mild NPDR (Level 1), 88.4% confidence.',
      },
      {
        id: 'AT-12',
        timestamp: '2026-09-02 10:15',
        action: 'confirmed',
        actor: 'Dr. R. Mehta',
        actorRole: 'doctor',
        details: 'Confirmed Mild NPDR. Non-referable. Scheduled annual follow-up.',
      },
    ],
  },
  {
    id: 'PT-10023',
    name: 'Mohammed Salim Ansari',
    age: 62,
    gender: 'M',
    phone: '+91 76543 21098',
    diabetesType: 'Type 2',
    diabetesDuration: 18,
    hba1c: 9.2,
    currentMedication: 'Insulin Glargine 20u',
    phcLocation: 'Manchar Rural Hospital',
    eye: 'OS',
    screeningDate: '2026-09-02',
    screeningTime: '09:51',
    imageQuality: {
      focus: 38,
      illumination: 44,
      fieldOfView: 52,
      overall: 'ungradable',
      score: 44,
      reason: 'Severe motion blur and low pupil illumination preventing clear fundus visualization.',
      guidance: 'Hold camera steady, allow 2 minutes for dark adaptation or dilation, and center on optic disc.',
    },
    drLevel: 0,
    drLabel: 'Ungradable Image — AI Analysis Blocked',
    confidence: 0,
    confidenceTier: 'mandatory',
    referable: false,
    aiStatus: 'error',
    reviewStatus: 'recapture',
    reviewNotes: 'Image quality below 70% threshold. Diagnostic AI grading was halted by Quality Gate to avoid misclassification. Immediate recapture advised.',
    lesions: {
      microaneurysms: { detected: false, count: 0, confidence: 0 },
      hemorrhages: { detected: false, count: 0, confidence: 0 },
      exudates: { detected: false, count: 0, confidence: 0 },
      neovascularization: { detected: false, confidence: 0 },
    },
    retinalStructures: {
      opticDisc: { detected: false, confidence: 0, location: 'N/A' },
      fovea: { detected: false, confidence: 0, location: 'N/A' },
      vessels: { segmented: false, confidence: 0 },
    },
    whyFlagged: [
      'Image Quality Gate failure: Score 44% < 70% minimum threshold',
      'Focus quality insufficient (38%) due to patient micro-tremor',
      'Illumination uneven (44%) — insufficient pupillary aperture',
      'Reliable clinical evaluation impossible without repeat capture',
    ],
    auditTrail: [
      {
        id: 'AT-20',
        timestamp: '2026-09-02 09:48',
        action: 'registered',
        actor: 'Ganesh Patil (HW)',
        actorRole: 'health_worker',
        details: 'Patient registered with history of blurred vision.',
      },
      {
        id: 'AT-21',
        timestamp: '2026-09-02 09:51',
        action: 'recapture_requested',
        actor: 'Quality Gate Module',
        actorRole: 'AI Engine',
        details: 'Quality score 44% — Ungradable. AI analysis safely halted. Guidance issued to field operator.',
      },
    ],
  },
  {
    id: 'PT-10024',
    name: 'Kamala Bai Rathod',
    age: 71,
    gender: 'F',
    phone: '+91 65432 10987',
    diabetesType: 'Type 2',
    diabetesDuration: 22,
    hba1c: 10.4,
    currentMedication: 'Premix Insulin 30/70',
    phcLocation: 'Junnar Taluka Hospital',
    eye: 'Both',
    screeningDate: '2026-09-02',
    screeningTime: '10:08',
    imageQuality: {
      focus: 91,
      illumination: 85,
      fieldOfView: 90,
      overall: 'gradable',
      score: 89,
    },
    drLevel: 3,
    drLabel: 'Severe Non-Proliferative Diabetic Retinopathy',
    confidence: 96.2,
    confidenceTier: 'priority',
    referable: true,
    aiStatus: 'complete',
    reviewStatus: 'referred',
    reviewedBy: 'Dr. A. Sharma (Ophthalmologist)',
    reviewedAt: '2026-09-02 10:40',
    reviewNotes: 'Severe NPDR confirmed. Extensive intraretinal hemorrhages in all 4 quadrants and venous beading noted. High risk of rapid progression to PDR. Fast-tracked urgent tertiary referral.',
    lesions: {
      microaneurysms: { detected: true, count: 28, confidence: 95, region: 'All 4 Quadrants' },
      hemorrhages: { detected: true, count: 19, confidence: 94, region: 'Extensive 4 Quadrants' },
      exudates: { detected: true, count: 8, confidence: 91, region: 'Macular Ring' },
      neovascularization: { detected: false, confidence: 92 },
    },
    retinalStructures: {
      opticDisc: { detected: true, confidence: 98, location: '(264, 187)' },
      fovea: { detected: true, confidence: 95, location: '(151, 203)' },
      vessels: { segmented: true, confidence: 94 },
    },
    whyFlagged: [
      'Intraretinal hemorrhages detected in all 4 retinal quadrants (4-2-1 rule)',
      'Marked venous beading and loops along superior retinal arcade',
      'Hard exudate circinate ring threatening central fovea',
      'High conversion risk to proliferative disease within 12 months',
    ],
    referral: {
      required: true,
      priority: 'urgent',
      center: 'Sassoon General Hospital & Regional Eye Institute, Pune',
      appointmentDate: '2026-09-08',
      appointmentTime: '09:00 AM',
      followUpDate: '2026-09-22',
      reason: 'Severe NPDR requiring urgent specialist evaluation, fundus fluorescein angiography (FFA), and potential panretinal photocoagulation.',
    },
    auditTrail: [
      {
        id: 'AT-30',
        timestamp: '2026-09-02 10:05',
        action: 'registered',
        actor: 'Anjali Deshmukh',
        actorRole: 'health_worker',
        details: 'Patient registered for acute visual assessment.',
      },
      {
        id: 'AT-31',
        timestamp: '2026-09-02 10:08',
        action: 'analyzed',
        actor: 'NetraRakshaq AI Engine v1.2',
        actorRole: 'AI Engine',
        details: 'AI predicted Severe NPDR (Level 3), 96.2% confidence. Priority referral auto-recommended.',
      },
      {
        id: 'AT-32',
        timestamp: '2026-09-02 10:40',
        action: 'referred',
        actor: 'Dr. A. Sharma',
        actorRole: 'doctor',
        details: 'Doctor validated Level 3 severity. Dispatched urgent SMS notification to patient and booked tertiary hospital slot.',
      },
    ],
  },
  {
    id: 'PT-10027',
    name: 'Deepak Singh Chauhan',
    age: 67,
    gender: 'M',
    phone: '+91 32109 87654',
    diabetesType: 'Type 2',
    diabetesDuration: 20,
    hba1c: 11.2,
    currentMedication: 'Insulin + Oral Hypoglycemics',
    phcLocation: 'Baramati Rural Center',
    eye: 'OD',
    screeningDate: '2026-09-02',
    screeningTime: '11:05',
    imageQuality: {
      focus: 92,
      illumination: 90,
      fieldOfView: 93,
      overall: 'gradable',
      score: 92,
    },
    drLevel: 4,
    drLabel: 'Proliferative Diabetic Retinopathy (PDR)',
    confidence: 97.4,
    confidenceTier: 'priority',
    referable: true,
    aiStatus: 'complete',
    reviewStatus: 'referred',
    reviewedBy: 'Dr. A. Sharma',
    reviewedAt: '2026-09-02 11:20',
    reviewNotes: 'Critical PDR confirmed. New abnormal blood vessels (neovascularization) visible at the optic disc edge. Urgent vitreoretinal intervention required.',
    lesions: {
      microaneurysms: { detected: true, count: 35, confidence: 96, region: 'Diffuse' },
      hemorrhages: { detected: true, count: 24, confidence: 95, region: 'Pre-retinal & Intraretinal' },
      exudates: { detected: true, count: 12, confidence: 92, region: 'Macular' },
      neovascularization: { detected: true, confidence: 97, region: 'Optic Disc Margin (NVD)' },
    },
    retinalStructures: {
      opticDisc: { detected: true, confidence: 99, location: '(265, 188)' },
      fovea: { detected: true, confidence: 96, location: '(150, 202)' },
      vessels: { segmented: true, confidence: 95 },
    },
    whyFlagged: [
      'Neovascularization detected on optic disc margin (NVD) with high confidence (97%)',
      'Pre-retinal preretinal hemorrhage hazard present',
      'Severe sight-threatening pathology — Level 4 Proliferative DR',
      'Immediate referral required within 48-72 hours',
    ],
    referral: {
      required: true,
      priority: 'urgent',
      center: 'Apex Vitreoretinal Institute, Pune',
      appointmentDate: '2026-09-05',
      appointmentTime: '08:30 AM',
      followUpDate: '2026-09-15',
      reason: 'PDR with active NVD. Immediate Anti-VEGF / Laser evaluation needed to avert vitreous hemorrhage.',
    },
    auditTrail: [
      {
        id: 'AT-40',
        timestamp: '2026-09-02 11:00',
        action: 'registered',
        actor: 'Rajesh Shinde (HW)',
        actorRole: 'health_worker',
        details: 'Patient registered with acute floaters and vision drop.',
      },
      {
        id: 'AT-41',
        timestamp: '2026-09-02 11:05',
        action: 'analyzed',
        actor: 'NetraRakshaq AI Engine v1.2',
        actorRole: 'AI Engine',
        details: 'AI predicted Proliferative DR (Level 4), 97.4% confidence. Urgent referral protocol triggered.',
      },
      {
        id: 'AT-42',
        timestamp: '2026-09-02 11:20',
        action: 'referred',
        actor: 'Dr. A. Sharma',
        actorRole: 'doctor',
        details: 'Doctor confirmed Level 4 PDR. Direct referral created with highest urgency.',
      },
    ],
  },
  {
    id: 'PT-10028',
    name: 'Lakshmi Bai Rao',
    age: 55,
    gender: 'F',
    phone: '+91 21098 76543',
    diabetesType: 'Type 2',
    diabetesDuration: 8,
    hba1c: 6.8,
    currentMedication: 'Metformin 500mg',
    phcLocation: 'Khed PHC',
    eye: 'OS',
    screeningDate: '2026-09-02',
    screeningTime: '11:28',
    imageQuality: {
      focus: 88,
      illumination: 86,
      fieldOfView: 90,
      overall: 'gradable',
      score: 88,
    },
    drLevel: 0,
    drLabel: 'No Diabetic Retinopathy',
    confidence: 94.8,
    confidenceTier: 'standard',
    referable: false,
    aiStatus: 'complete',
    reviewStatus: 'reviewed',
    reviewedBy: 'Dr. R. Mehta',
    reviewedAt: '2026-09-02 11:45',
    reviewNotes: 'Normal healthy retina. No microvascular anomalies observed. Patient advised to maintain good glycemic control and return in 1 year.',
    lesions: {
      microaneurysms: { detected: false, count: 0, confidence: 93 },
      hemorrhages: { detected: false, count: 0, confidence: 95 },
      exudates: { detected: false, count: 0, confidence: 94 },
      neovascularization: { detected: false, confidence: 97 },
    },
    retinalStructures: {
      opticDisc: { detected: true, confidence: 97, location: '(265, 188)' },
      fovea: { detected: true, confidence: 94, location: '(150, 202)' },
      vessels: { segmented: true, confidence: 93 },
    },
    whyFlagged: [
      'Zero microaneurysms or retinal hemorrhages detected',
      'Normal vessel caliber with healthy optic disc margins',
      'Normal screening result — Level 0 No DR',
    ],
    referral: {
      required: false,
      priority: 'followup',
      center: 'Khed PHC Center',
      followUpDate: '2027-09-02',
      reason: 'Routine annual screening recommendation for stable diabetic patient.',
    },
    auditTrail: [
      {
        id: 'AT-50',
        timestamp: '2026-09-02 11:25',
        action: 'registered',
        actor: 'Anjali Deshmukh',
        actorRole: 'health_worker',
        details: 'Patient registered for annual checkup.',
      },
      {
        id: 'AT-51',
        timestamp: '2026-09-02 11:28',
        action: 'analyzed',
        actor: 'NetraRakshaq AI Engine v1.2',
        actorRole: 'AI Engine',
        details: 'Predicted Level 0 (No DR), 94.8% confidence.',
      },
      {
        id: 'AT-52',
        timestamp: '2026-09-02 11:45',
        action: 'confirmed',
        actor: 'Dr. R. Mehta',
        actorRole: 'doctor',
        details: 'Normal fundus confirmed. 12-month recall assigned.',
      },
    ],
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'APT-901',
    patientId: 'PT-10024',
    patientName: 'Kamala Bai Rathod',
    date: '2026-09-08',
    time: '09:00 AM',
    center: 'Sassoon General Hospital & Regional Eye Institute, Pune',
    type: 'specialist_review',
    priority: 'urgent',
    status: 'confirmed',
    notes: 'Severe NPDR examination and FFA workup.',
  },
  {
    id: 'APT-902',
    patientId: 'PT-10027',
    patientName: 'Deepak Singh Chauhan',
    date: '2026-09-05',
    time: '08:30 AM',
    center: 'Apex Vitreoretinal Institute, Pune',
    type: 'specialist_review',
    priority: 'urgent',
    status: 'confirmed',
    notes: 'PDR with NVD. Anti-VEGF / Laser consultation.',
  },
  {
    id: 'APT-903',
    patientId: 'PT-10021',
    patientName: 'Rajesh Kumar Verma',
    date: '2026-09-12',
    time: '10:30 AM',
    center: 'District Eye Hospital, Aundh, Pune',
    type: 'specialist_review',
    priority: 'high',
    status: 'confirmed',
    notes: 'Moderate NPDR follow-up and dilated evaluation.',
  },
  {
    id: 'APT-904',
    patientId: 'PT-10023',
    patientName: 'Mohammed Salim Ansari',
    date: '2026-09-04',
    time: '11:00 AM',
    center: 'Manchar Rural Hospital PHC',
    type: 'recapture',
    priority: 'high',
    status: 'confirmed',
    notes: 'Re-screening following ungradable image quality check.',
  },
];

export const DEMO_PRESETS: Record<string, { label: string; desc: string; output: MLScreeningOutput }> = {
  moderate_npdr: {
    label: 'Moderate NPDR (Level 2) — Referable',
    desc: 'Typical referable case with microaneurysms, hemorrhages, and parafoveal exudates.',
    output: {
      image_quality: {
        gradable: true,
        focus: 94,
        illumination: 88,
        field_of_view: 92,
        overall_score: 91,
      },
      dr_prediction: {
        level: 2,
        label: 'Moderate Non-Proliferative Diabetic Retinopathy',
        confidence: 93.1,
        referable: true,
        tier: 'standard',
      },
      retinal_structures: {
        optic_disc: { detected: true, confidence: 97, location: '(265, 188)' },
        fovea: { detected: true, confidence: 94, location: '(150, 202)' },
        vessels: { segmented: true, confidence: 92, mask_status: 'ready' },
      },
      lesions: [
        { name: 'Microaneurysms', detected: true, count: 14, confidence: 91, region: 'Pericentral, Temporal' },
        { name: 'Hemorrhages', detected: true, count: 6, confidence: 87, region: 'Inferior Temporal' },
        { name: 'Exudates', detected: true, count: 3, confidence: 90, region: 'Parafoveal' },
        { name: 'Neovascularization', detected: false, count: 0, confidence: 88 },
      ],
      explainability: {
        gradcam_available: true,
        annotated_image_available: true,
        why_flagged_summary: [
          'Multiple microaneurysms (14) across inferior temporal vascular arcades',
          'Scattered flame and dot-blot hemorrhages (6)',
          'Hard exudates adjacent to macular boundary',
          'Meets referral threshold per ICDR criteria (Level 2+)',
        ],
        recommended_action: 'Doctor Review Recommended. Schedule specialist referral within 2-4 weeks.',
      },
      enhancement: {
        clahe_applied: true,
        illumination_normalized: true,
        denoised: true,
        status: 'enhanced',
      },
    },
  },
  severe_npdr: {
    label: 'Severe NPDR (Level 3) — Priority Referral',
    desc: 'Severe non-proliferative changes with 4-quadrant hemorrhages and venous beading.',
    output: {
      image_quality: {
        gradable: true,
        focus: 91,
        illumination: 85,
        field_of_view: 90,
        overall_score: 89,
      },
      dr_prediction: {
        level: 3,
        label: 'Severe Non-Proliferative Diabetic Retinopathy',
        confidence: 96.2,
        referable: true,
        tier: 'priority',
      },
      retinal_structures: {
        optic_disc: { detected: true, confidence: 98, location: '(264, 187)' },
        fovea: { detected: true, confidence: 95, location: '(151, 203)' },
        vessels: { segmented: true, confidence: 94, mask_status: 'ready' },
      },
      lesions: [
        { name: 'Microaneurysms', detected: true, count: 28, confidence: 95, region: 'All 4 Quadrants' },
        { name: 'Hemorrhages', detected: true, count: 19, confidence: 94, region: 'All 4 Quadrants' },
        { name: 'Exudates', detected: true, count: 8, confidence: 91, region: 'Macular Ring' },
        { name: 'Neovascularization', detected: false, count: 0, confidence: 92 },
      ],
      explainability: {
        gradcam_available: true,
        annotated_image_available: true,
        why_flagged_summary: [
          'Extensive retinal hemorrhages spanning all four quadrants (4-2-1 rule met)',
          'Venous beading observed along the superior temporal vein',
          'Foveal circinate ring indicating severe exudative leakage',
        ],
        recommended_action: 'Urgent Doctor Review. Urgent referral to tertiary vitreoretinal center within 7 days.',
      },
      enhancement: {
        clahe_applied: true,
        illumination_normalized: true,
        denoised: true,
        status: 'enhanced',
      },
    },
  },
  proliferative_dr: {
    label: 'Proliferative DR (Level 4) — Critical / Urgent',
    desc: 'Sight-threatening retinopathy with active neovascularization at optic disc.',
    output: {
      image_quality: {
        gradable: true,
        focus: 92,
        illumination: 90,
        field_of_view: 93,
        overall_score: 92,
      },
      dr_prediction: {
        level: 4,
        label: 'Proliferative Diabetic Retinopathy (PDR)',
        confidence: 97.4,
        referable: true,
        tier: 'priority',
      },
      retinal_structures: {
        optic_disc: { detected: true, confidence: 99, location: '(265, 188)' },
        fovea: { detected: true, confidence: 96, location: '(150, 202)' },
        vessels: { segmented: true, confidence: 95, mask_status: 'ready' },
      },
      lesions: [
        { name: 'Microaneurysms', detected: true, count: 35, confidence: 96, region: 'Diffuse' },
        { name: 'Hemorrhages', detected: true, count: 24, confidence: 95, region: 'Pre-retinal & Intraretinal' },
        { name: 'Exudates', detected: true, count: 12, confidence: 92, region: 'Macular' },
        { name: 'Neovascularization', detected: true, count: 2, confidence: 97, region: 'Optic Disc Margin (NVD)' },
      ],
      explainability: {
        gradcam_available: true,
        annotated_image_available: true,
        why_flagged_summary: [
          'High-confidence detection of Neovascularization on the Disc (NVD)',
          'Extensive fibrovascular proliferation and pre-retinal hemorrhage',
          'Immediate risk of non-clearing vitreous hemorrhage or tractional detachment',
        ],
        recommended_action: 'CRITICAL URGENCY: Expedite specialist retinal surgeon evaluation within 48-72 hours.',
      },
      enhancement: {
        clahe_applied: true,
        illumination_normalized: true,
        denoised: true,
        status: 'enhanced',
      },
    },
  },
  mild_npdr: {
    label: 'Mild NPDR (Level 1) — Non-Referable',
    desc: 'Early microvascular changes with isolated microaneurysms only.',
    output: {
      image_quality: {
        gradable: true,
        focus: 87,
        illumination: 82,
        field_of_view: 89,
        overall_score: 86,
      },
      dr_prediction: {
        level: 1,
        label: 'Mild Non-Proliferative Diabetic Retinopathy',
        confidence: 88.4,
        referable: false,
        tier: 'standard',
      },
      retinal_structures: {
        optic_disc: { detected: true, confidence: 96, location: '(268, 185)' },
        fovea: { detected: true, confidence: 92, location: '(148, 200)' },
        vessels: { segmented: true, confidence: 90, mask_status: 'ready' },
      },
      lesions: [
        { name: 'Microaneurysms', detected: true, count: 4, confidence: 84, region: 'Superior Temporal' },
        { name: 'Hemorrhages', detected: false, count: 0, confidence: 91 },
        { name: 'Exudates', detected: false, count: 0, confidence: 89 },
        { name: 'Neovascularization', detected: false, count: 0, confidence: 95 },
      ],
      explainability: {
        gradcam_available: true,
        annotated_image_available: true,
        why_flagged_summary: [
          'Isolated microaneurysms (4) detected without retinal hemorrhages',
          'Macular center free of exudates or edema',
          'Non-referable threshold per ICDR criteria',
        ],
        recommended_action: 'Routine annual screening. Emphasize glycemic and blood pressure management.',
      },
      enhancement: {
        clahe_applied: true,
        illumination_normalized: true,
        denoised: true,
        status: 'enhanced',
      },
    },
  },
  no_dr: {
    label: 'No DR (Level 0) — Normal Retina',
    desc: 'Clear healthy fundus with zero microvascular findings.',
    output: {
      image_quality: {
        gradable: true,
        focus: 88,
        illumination: 86,
        field_of_view: 90,
        overall_score: 88,
      },
      dr_prediction: {
        level: 0,
        label: 'No Diabetic Retinopathy',
        confidence: 94.8,
        referable: false,
        tier: 'standard',
      },
      retinal_structures: {
        optic_disc: { detected: true, confidence: 97, location: '(265, 188)' },
        fovea: { detected: true, confidence: 94, location: '(150, 202)' },
        vessels: { segmented: true, confidence: 93, mask_status: 'ready' },
      },
      lesions: [
        { name: 'Microaneurysms', detected: false, count: 0, confidence: 93 },
        { name: 'Hemorrhages', detected: false, count: 0, confidence: 95 },
        { name: 'Exudates', detected: false, count: 0, confidence: 94 },
        { name: 'Neovascularization', detected: false, count: 0, confidence: 97 },
      ],
      explainability: {
        gradcam_available: true,
        annotated_image_available: true,
        why_flagged_summary: [
          'No microaneurysms or retinal hemorrhages detected',
          'Clear vascular arcades and sharp optic disc cup/rim ratio',
          'Normal screening result',
        ],
        recommended_action: 'Maintain regular annual screening. Healthy retinal baseline established.',
      },
      enhancement: {
        clahe_applied: true,
        illumination_normalized: true,
        denoised: true,
        status: 'enhanced',
      },
    },
  },
  ungradable: {
    label: 'Ungradable Image — Quality Gate Block',
    desc: 'Simulates poor focus and illumination failure triggering smart recapture instructions.',
    output: {
      image_quality: {
        gradable: false,
        focus: 38,
        illumination: 44,
        field_of_view: 52,
        overall_score: 44,
        failure_reasons: [
          'Poor Focus: Insufficient edge sharpness across retinal vascular branches',
          'Poor Illumination: Uneven lighting with severe underexposure in nasal field',
          'Incomplete Field of View: Optic disc partially clipped at frame boundary',
        ],
        recapture_guidance: 'Hold camera steady, allow dark adaptation for natural pupil dilation, center optic disc, and recapture.',
      },
      dr_prediction: {
        level: 0,
        label: 'Ungradable — Screening Halted',
        confidence: 0,
        referable: false,
        tier: 'mandatory',
      },
      retinal_structures: {
        optic_disc: { detected: false, confidence: 0, location: 'N/A' },
        fovea: { detected: false, confidence: 0, location: 'N/A' },
        vessels: { segmented: false, confidence: 0, mask_status: 'failed' },
      },
      lesions: [],
      explainability: {
        gradcam_available: false,
        annotated_image_available: false,
        why_flagged_summary: [
          'CRITICAL: Image quality insufficient for reliable AI analysis',
          'Model inference blocked to prevent false negatives or false positives',
          'Immediate physical recapture required at screening point',
        ],
        recommended_action: 'RECAPTURE IMAGE: Operator must follow guidance and re-acquire retinal fundus photo.',
      },
      enhancement: {
        clahe_applied: false,
        illumination_normalized: false,
        denoised: false,
        status: 'bypassed',
      },
    },
  },
};
