import { useState } from 'react';
import { FileText, Printer, Download, Share2, CheckCircle2, AlertTriangle } from 'lucide-react';
import { Badge, ConfidenceMeter, QualityBar } from '../components/ui/primitives';
import { FundusImage } from '../components/ui/FundusViewer';
import { MOCK_PATIENTS } from '../lib/mockData';
import { DR_LEVEL_LABELS } from '../lib/types';

const patient = MOCK_PATIENTS[0]; // PT-10021

function ReportSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2">
        <h3 className="text-xs font-semibold text-slate-300 uppercase tracking-wider">{title}</h3>
        <div className="flex-1 border-t border-slate-700/50" />
      </div>
      {children}
    </div>
  );
}

export function Reports() {
  const [selectedPatient, setSelectedPatient] = useState(patient.id);
  const p = MOCK_PATIENTS.find(x => x.id === selectedPatient) ?? MOCK_PATIENTS[0];

  return (
    <div className="p-6 space-y-4">
      {/* Controls */}
      <div className="flex items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-semibold text-slate-100">Screening Report</h1>
          <p className="text-sm text-slate-400 mt-0.5">Auto-generated AI-assisted screening report</p>
        </div>
        <div className="flex items-center gap-2">
          <select
            value={selectedPatient}
            onChange={e => setSelectedPatient(e.target.value)}
            className="bg-slate-800 border border-slate-700 text-slate-300 text-sm rounded-lg px-3 py-2 outline-none cursor-pointer"
          >
            {MOCK_PATIENTS.filter(p => p.aiStatus === 'complete').map(p => (
              <option key={p.id} value={p.id}>{p.id}</option>
            ))}
          </select>
          <button className="flex items-center gap-1.5 px-3 py-2 bg-slate-800 border border-slate-700 text-slate-300 text-sm rounded-lg hover:bg-slate-700 transition-colors cursor-pointer">
            <Printer size={14} /> Print
          </button>
          <button className="flex items-center gap-1.5 px-3 py-2 bg-slate-800 border border-slate-700 text-slate-300 text-sm rounded-lg hover:bg-slate-700 transition-colors cursor-pointer">
            <Download size={14} /> PDF
          </button>
          <button className="flex items-center gap-1.5 px-3 py-2 bg-cyan-500 text-slate-950 text-sm font-semibold rounded-lg hover:bg-cyan-400 transition-colors cursor-pointer">
            <Share2 size={14} /> Share
          </button>
        </div>
      </div>

      {/* Report document */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden">
        {/* Report header */}
        <div className="px-8 py-6 border-b border-slate-800 bg-slate-950/40">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-cyan-500/10 border border-cyan-500/20 flex items-center justify-center">
                <FileText size={18} className="text-cyan-400" />
              </div>
              <div>
                <h2 className="text-base font-semibold text-slate-100">NetraRakshaq Screening Report</h2>
                <p className="text-xs text-slate-500 font-mono">Report ID: NR-{p.id}-{p.screeningDate.replace(/-/g, '')}</p>
              </div>
            </div>
            <div className="text-right">
              <p className="text-xs text-slate-400">Generated: {p.screeningDate} at {p.screeningTime}</p>
              <p className="text-[10px] text-slate-600 mt-0.5">AI-assisted screening · Demo data</p>
            </div>
          </div>
        </div>

        <div className="px-8 py-6 space-y-8">
          {/* Disclaimer */}
          <div className="flex items-start gap-3 p-3 bg-amber-500/6 border border-amber-500/20 rounded-lg">
            <AlertTriangle size={13} className="text-amber-400 flex-shrink-0 mt-0.5" />
            <p className="text-xs text-amber-200/80 leading-relaxed">
              <strong className="text-amber-300">AI-assisted screening — clinician review recommended.</strong> Results generated by AI model and have not been verified by a licensed ophthalmologist. Not for direct clinical use without qualified review. <span className="text-amber-400/60">Demo data only.</span>
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* Left column: fundus image */}
            <div className="space-y-4">
              <ReportSection title="Retinal Image">
                <div className="rounded-xl overflow-hidden bg-black fundus-shadow w-full aspect-square">
                  <FundusImage mode="gradcam" heatmapOpacity={0.5} />
                </div>
                <p className="text-[10px] text-slate-600 text-center font-mono">Grad-CAM overlay · Demo visualization</p>
              </ReportSection>

              <ReportSection title="Image Quality">
                <div className="space-y-2.5">
                  <QualityBar label="Focus" value={p.imageQuality.focus} />
                  <QualityBar label="Illumination" value={p.imageQuality.illumination} />
                  <QualityBar label="Field of View" value={p.imageQuality.fieldOfView} />
                  <div className="flex items-center justify-between pt-1">
                    <span className="text-xs text-slate-400">Overall score</span>
                    <span className={`text-sm font-mono font-semibold ${p.imageQuality.score >= 70 ? 'text-emerald-400' : 'text-red-400'}`}>
                      {p.imageQuality.score}%
                    </span>
                  </div>
                </div>
              </ReportSection>
            </div>

            {/* Right columns: findings */}
            <div className="lg:col-span-2 space-y-6">
              {/* Patient info */}
              <ReportSection title="Patient Information">
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                  {[
                    { label: 'Patient ID', value: p.id },
                    { label: 'Age', value: `${p.age} years` },
                    { label: 'Gender', value: p.gender === 'M' ? 'Male' : 'Female' },
                    { label: 'DM Duration', value: `${p.diabetesDuration} years` },
                  ].map(({ label, value }) => (
                    <div key={label}>
                      <p className="text-[10px] text-slate-500 uppercase tracking-wide">{label}</p>
                      <p className="text-sm font-medium text-slate-200 mt-0.5 font-mono">{value}</p>
                    </div>
                  ))}
                </div>
              </ReportSection>

              {/* DR Assessment */}
              <ReportSection title="DR Assessment">
                <div className="bg-slate-800/50 rounded-xl p-4 space-y-3">
                  <div className="flex items-start justify-between">
                    <div>
                      <p className="text-base font-semibold text-slate-100">{p.drLabel}</p>
                      <p className="text-xs text-slate-500 mt-0.5">International Clinical DR Scale</p>
                    </div>
                    <div className="text-right">
                      <span className={`text-3xl font-bold font-mono ${p.drLevel >= 3 ? 'text-red-400' : p.drLevel >= 2 ? 'text-amber-400' : p.drLevel >= 1 ? 'text-yellow-400' : 'text-emerald-400'}`}>
                        {p.drLevel}
                        <span className="text-lg text-slate-600">/4</span>
                      </span>
                    </div>
                  </div>
                  <ConfidenceMeter value={p.confidence} />
                  <div className="flex items-center gap-3">
                    <Badge variant={p.referable ? 'danger' : 'success'} size="md">
                      {p.referable ? 'REFERABLE' : 'NON-REFERABLE'}
                    </Badge>
                    <span className="text-xs text-slate-500">
                      {p.referable ? 'Referral to ophthalmologist recommended' : 'Annual follow-up recommended'}
                    </span>
                  </div>
                </div>
              </ReportSection>

              {/* Lesion findings */}
              <ReportSection title="Lesion Findings">
                <div className="grid grid-cols-2 gap-3">
                  {[
                    { name: 'Microaneurysms', data: p.lesions.microaneurysms },
                    { name: 'Hemorrhages', data: p.lesions.hemorrhages },
                    { name: 'Exudates', data: p.lesions.exudates },
                    { name: 'Neovascularization', data: p.lesions.neovascularization },
                  ].map(({ name, data }) => (
                    <div key={name} className="bg-slate-800/40 rounded-lg p-3">
                      <div className="flex items-center justify-between mb-1.5">
                        <span className="text-xs font-medium text-slate-300">{name}</span>
                        {data.detected
                          ? <span className="text-[10px] text-red-400 font-medium">DETECTED</span>
                          : <span className="text-[10px] text-emerald-400 font-medium">NOT DETECTED</span>
                        }
                      </div>
                      {data.count !== undefined && data.detected && (
                        <p className="text-xs text-slate-500">Count: <span className="text-slate-300 font-mono">{data.count}</span></p>
                      )}
                      <p className="text-[10px] text-slate-600 font-mono">Confidence: {data.confidence}%</p>
                    </div>
                  ))}
                </div>
              </ReportSection>

              {/* Recommendation */}
              <ReportSection title="Recommendation">
                <div className={`flex items-start gap-3 p-4 rounded-xl border ${p.referable ? 'bg-red-500/5 border-red-500/20' : 'bg-emerald-500/5 border-emerald-500/20'}`}>
                  {p.referable
                    ? <AlertTriangle size={16} className="text-red-400 flex-shrink-0 mt-0.5" />
                    : <CheckCircle2 size={16} className="text-emerald-400 flex-shrink-0 mt-0.5" />
                  }
                  <div>
                    <p className={`text-sm font-semibold ${p.referable ? 'text-red-300' : 'text-emerald-300'}`}>
                      {p.referable ? 'Refer to Ophthalmologist' : 'Annual Monitoring Recommended'}
                    </p>
                    <p className="text-xs text-slate-400 mt-1 leading-relaxed">
                      {p.referable
                        ? 'AI model identifies referable diabetic retinopathy (Level 2+). Prompt ophthalmologist evaluation is advised. This recommendation is based on AI model output and must be confirmed by a qualified clinician.'
                        : 'No referable diabetic retinopathy detected by the AI model. Annual diabetic eye screening is recommended. This result must be confirmed by a qualified clinician.'}
                    </p>
                  </div>
                </div>
              </ReportSection>

              {/* Sign-off area */}
              <ReportSection title="Clinical Review">
                <div className="bg-slate-800/40 rounded-lg p-4">
                  {p.reviewedBy ? (
                    <div>
                      <p className="text-xs text-slate-400">Reviewed by</p>
                      <p className="text-sm font-medium text-slate-200 mt-0.5">{p.reviewedBy}</p>
                      <p className="text-[10px] text-slate-500 mt-1 font-mono">Review status: {p.reviewStatus.replace('_', ' ')}</p>
                    </div>
                  ) : (
                    <p className="text-sm text-slate-500 italic">Pending clinical review</p>
                  )}
                </div>
              </ReportSection>
            </div>
          </div>

          <div className="border-t border-slate-800 pt-4">
            <p className="text-[10px] text-slate-600 text-center leading-relaxed">
              NetraRakshaq · Explainable AI for Diabetic Retinopathy Screening · Prototype v1.0 · Demo data only · Not approved for clinical use without regulatory clearance
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
